### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by RandomUsername12222** [Monsters-RPG-game/Messages#67]
# Monsters messages roadmap

## Features for `1.0`:
- [X] Messages system
- [X] Live chat system
- [ ] Email system

### Messages system
- [X] Send message
- [X] Read message
- [X] Get message
- [X] Get unread message
- [ ] Change user messages to 'system' - aka "send help req etc"

### Live chat system
- [X] Send message
- [X] Read message
- [X] Get message
- [X] Get unread message

### Email system
- [ ] Send email
- [ ] Generate code to change password
- [ ] Generate code to verify email
